// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as LanguagesIndexImport } from './routes/languages/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'
import { Route as AttributeGroupsIndexImport } from './routes/attribute-groups/index'
import { Route as LanguagesNewImport } from './routes/languages/new'
import { Route as CategoriesNewImport } from './routes/categories/new'
import { Route as AttributeGroupsNewImport } from './routes/attribute-groups/new'
import { Route as LanguagesLanguageIdEditImport } from './routes/languages/$languageId.edit'
import { Route as CategoriesCategoryIdEditImport } from './routes/categories/$categoryId.edit'
import { Route as AttributeGroupsAttributeGroupIdEditImport } from './routes/attribute-groups/$attributeGroupId.edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LanguagesIndexRoute = LanguagesIndexImport.update({
  path: '/languages/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

const AttributeGroupsIndexRoute = AttributeGroupsIndexImport.update({
  path: '/attribute-groups/',
  getParentRoute: () => rootRoute,
} as any)

const LanguagesNewRoute = LanguagesNewImport.update({
  path: '/languages/new',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesNewRoute = CategoriesNewImport.update({
  path: '/categories/new',
  getParentRoute: () => rootRoute,
} as any)

const AttributeGroupsNewRoute = AttributeGroupsNewImport.update({
  path: '/attribute-groups/new',
  getParentRoute: () => rootRoute,
} as any)

const LanguagesLanguageIdEditRoute = LanguagesLanguageIdEditImport.update({
  path: '/languages/$languageId/edit',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesCategoryIdEditRoute = CategoriesCategoryIdEditImport.update({
  path: '/categories/$categoryId/edit',
  getParentRoute: () => rootRoute,
} as any)

const AttributeGroupsAttributeGroupIdEditRoute =
  AttributeGroupsAttributeGroupIdEditImport.update({
    path: '/attribute-groups/$attributeGroupId/edit',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/attribute-groups/new': {
      preLoaderRoute: typeof AttributeGroupsNewImport
      parentRoute: typeof rootRoute
    }
    '/categories/new': {
      preLoaderRoute: typeof CategoriesNewImport
      parentRoute: typeof rootRoute
    }
    '/languages/new': {
      preLoaderRoute: typeof LanguagesNewImport
      parentRoute: typeof rootRoute
    }
    '/attribute-groups/': {
      preLoaderRoute: typeof AttributeGroupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/': {
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/languages/': {
      preLoaderRoute: typeof LanguagesIndexImport
      parentRoute: typeof rootRoute
    }
    '/attribute-groups/$attributeGroupId/edit': {
      preLoaderRoute: typeof AttributeGroupsAttributeGroupIdEditImport
      parentRoute: typeof rootRoute
    }
    '/categories/$categoryId/edit': {
      preLoaderRoute: typeof CategoriesCategoryIdEditImport
      parentRoute: typeof rootRoute
    }
    '/languages/$languageId/edit': {
      preLoaderRoute: typeof LanguagesLanguageIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  AttributeGroupsNewRoute,
  CategoriesNewRoute,
  LanguagesNewRoute,
  AttributeGroupsIndexRoute,
  CategoriesIndexRoute,
  LanguagesIndexRoute,
  AttributeGroupsAttributeGroupIdEditRoute,
  CategoriesCategoryIdEditRoute,
  LanguagesLanguageIdEditRoute,
])
