/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LnIndexImport } from './routes/$ln/index'
import { Route as LnPostsImport } from './routes/$ln/posts'
import { Route as LnErrorImport } from './routes/$ln/error'
import { Route as LnPostsIndexImport } from './routes/$ln/posts/index'
import { Route as LnPostsPostIdImport } from './routes/$ln/posts/$postId'
import { Route as LnCategorySlugImport } from './routes/$ln/category.$slug'

// Create/Update Routes

const LnIndexRoute = LnIndexImport.update({
  path: '/$ln/',
  getParentRoute: () => rootRoute,
} as any)

const LnPostsRoute = LnPostsImport.update({
  path: '/$ln/posts',
  getParentRoute: () => rootRoute,
} as any)

const LnErrorRoute = LnErrorImport.update({
  path: '/$ln/error',
  getParentRoute: () => rootRoute,
} as any)

const LnPostsIndexRoute = LnPostsIndexImport.update({
  path: '/',
  getParentRoute: () => LnPostsRoute,
} as any)

const LnPostsPostIdRoute = LnPostsPostIdImport.update({
  path: '/$postId',
  getParentRoute: () => LnPostsRoute,
} as any)

const LnCategorySlugRoute = LnCategorySlugImport.update({
  path: '/$ln/category/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$ln/error': {
      preLoaderRoute: typeof LnErrorImport
      parentRoute: typeof rootRoute
    }
    '/$ln/posts': {
      preLoaderRoute: typeof LnPostsImport
      parentRoute: typeof rootRoute
    }
    '/$ln/': {
      preLoaderRoute: typeof LnIndexImport
      parentRoute: typeof rootRoute
    }
    '/$ln/category/$slug': {
      preLoaderRoute: typeof LnCategorySlugImport
      parentRoute: typeof rootRoute
    }
    '/$ln/posts/$postId': {
      preLoaderRoute: typeof LnPostsPostIdImport
      parentRoute: typeof LnPostsImport
    }
    '/$ln/posts/': {
      preLoaderRoute: typeof LnPostsIndexImport
      parentRoute: typeof LnPostsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LnErrorRoute,
  LnPostsRoute.addChildren([LnPostsPostIdRoute, LnPostsIndexRoute]),
  LnIndexRoute,
  LnCategorySlugRoute,
])

/* prettier-ignore-end */
