/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LnImport } from './routes/$ln'
import { Route as LnPostsImport } from './routes/$ln/posts'
import { Route as LnErrorImport } from './routes/$ln/error'
import { Route as LnPostsIndexImport } from './routes/$ln/posts/index'
import { Route as LnPostsPostIdImport } from './routes/$ln/posts/$postId'

// Create/Update Routes

const LnRoute = LnImport.update({
  path: '/$ln',
  getParentRoute: () => rootRoute,
} as any)

const LnPostsRoute = LnPostsImport.update({
  path: '/posts',
  getParentRoute: () => LnRoute,
} as any)

const LnErrorRoute = LnErrorImport.update({
  path: '/error',
  getParentRoute: () => LnRoute,
} as any)

const LnPostsIndexRoute = LnPostsIndexImport.update({
  path: '/',
  getParentRoute: () => LnPostsRoute,
} as any)

const LnPostsPostIdRoute = LnPostsPostIdImport.update({
  path: '/$postId',
  getParentRoute: () => LnPostsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$ln': {
      preLoaderRoute: typeof LnImport
      parentRoute: typeof rootRoute
    }
    '/$ln/error': {
      preLoaderRoute: typeof LnErrorImport
      parentRoute: typeof LnImport
    }
    '/$ln/posts': {
      preLoaderRoute: typeof LnPostsImport
      parentRoute: typeof LnImport
    }
    '/$ln/posts/$postId': {
      preLoaderRoute: typeof LnPostsPostIdImport
      parentRoute: typeof LnPostsImport
    }
    '/$ln/posts/': {
      preLoaderRoute: typeof LnPostsIndexImport
      parentRoute: typeof LnPostsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LnRoute.addChildren([
    LnErrorRoute,
    LnPostsRoute.addChildren([LnPostsPostIdRoute, LnPostsIndexRoute]),
  ]),
])

/* prettier-ignore-end */
