CREATE TABLE IF NOT EXISTS admins (
  id       SERIAL PRIMARY KEY,
  name     VARCHAR(255),
  surname  VARCHAR(255),
  email    VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (email)
);
